import React, { useMemo, useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import { ArrowRight, BriefcaseBusiness, Compass, Network, ShieldCheck, Sparkles, Users } from "lucide-react";
import "./NovaSite.css";
import "./EnginePages.css";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL || "https://novarch-api.onrender.com";

function Shell({children}){
  return <div className="nv-site"><header className="nv-nav"><Link to="/" className="nv-brand"><span className="nv-mark">N</span><span>NOVARCH</span></Link><nav className="nv-links"><Link to="/systems">Systems</Link><Link to="/work">Work</Link><Link to="/launch">Launch</Link><Link to="/company">Company</Link></nav><a className="nv-nav-cta" href="mailto:novarch-ai@gmail.com?subject=NOVARCH%20conversation">Start a conversation <ArrowRight size={15}/></a></header>{children}<footer className="nv-footer"><div className="nv-brand"><span className="nv-mark">N</span><span>NOVARCH</span></div><div><Link to="/community">Community</Link><Link to="/talent">Talent</Link><Link to="/advisors">Advisors</Link><Link to="/manifesto">Manifesto</Link><Link to="/datenschutz">Privacy</Link></div><small>Ilmenau, Germany · International by design</small></footer></div>
}

function InterestForm({purpose,button="Join",note}){
  const [email,setEmail]=useState(""); const [state,setState]=useState("idle"); const [message,setMessage]=useState("");
  const source=useMemo(()=>{const p=new URLSearchParams(window.location.search);return p.get("utm_source")||p.get("ref")||window.location.pathname},[]);
  async function submit(e){e.preventDefault();if(!email.trim())return;setState("loading");setMessage("");try{const r=await axios.post(`${BACKEND_URL}/api/subscribe`,{email:email.trim().toLowerCase(),purpose,source,privacy_acknowledged:true});setState("success");setMessage(r.data.message||"You're in.");setEmail("")}catch(err){setState("error");setMessage(err.response?.data?.detail||"Unable to submit right now.")}}
  return <form className="engine-form" onSubmit={submit}><label>Email address</label><div><input required type="email" placeholder="you@company.com" value={email} onChange={e=>setEmail(e.target.value)} disabled={state==="loading"}/><button disabled={state==="loading"}>{state==="loading"?"Sending…":button}<ArrowRight size={15}/></button></div><small>{note} See our <Link to="/datenschutz">privacy notice</Link>.</small>{message&&<p className={`engine-message ${state}`}>{message}</p>}</form>
}

function EngineHero({kicker,title,copy,children}){return <section className="engine-hero"><span>{kicker}</span><h1>{title}</h1><p>{copy}</p>{children}</section>}

export function LaunchPage(){return <Shell><main className="engine-main"><EngineHero kicker="Launch / Early access" title="Get closer to what NOVARCH is building." copy="A reusable launch surface for new systems, private AI experiments and productized infrastructure. Join once; we will only contact you for the launch path you selected."><InterestForm purpose="novarch_launch" button="Join early access" note="By joining, you ask NOVARCH to contact you about selected launches."/></EngineHero><section className="engine-grid"><article><Sparkles/><small>Product drops</small><h2>New systems as they become repeatable.</h2><p>We will publish bounded tools and operating systems when they have earned the right to become products.</p></article><article><ShieldCheck/><small>Private systems</small><h2>Ownership over dependency.</h2><p>Private and controlled AI infrastructure is part of the long-term NOVARCH product thesis.</p></article><article><Compass/><small>Design partners</small><h2>Build before the category hardens.</h2><p>Selected companies and institutions can work with us before a system is fully productized.</p></article></section></main></Shell>}

export function CommunityPage(){return <Shell><main className="engine-main"><EngineHero kicker="Community" title="A network for people building systems, not hype." copy="The NOVARCH community starts small: founders, operators, technologists, institutional builders and people interested in owning more of their digital infrastructure."><InterestForm purpose="novarch_community" button="Join the community list" note="This is an interest list, not a promise of immediate admission or an active public community."/></EngineHero><section className="engine-grid"><article><Users/><small>Who it is for</small><h2>Builders and operators.</h2><p>People working on real businesses, products, institutions, automation, AI, privacy and operational systems.</p></article><article><Network/><small>What it can become</small><h2>Access, exchange and collaboration.</h2><p>Private sessions, launch access, local meetups, product experiments and cross-border collaboration as the network earns density.</p></article><article><ShieldCheck/><small>What it is not</small><h2>No fake community theatre.</h2><p>We will not display vanity member counts or manufacture activity. The surface grows with actual participation.</p></article></section></main></Shell>}

export function TalentPage(){return <Shell><main className="engine-main"><EngineHero kicker="Talent" title="Build the company that builds the systems." copy="NOVARCH is assembling a cross-border team around product, AI, engineering, operations, growth and institutional delivery. The pipeline stays open even when a named role is not."><InterestForm purpose="novarch_talent" button="Enter talent pipeline" note="By joining, you allow NOVARCH to contact you about relevant future roles or project work."/></EngineHero><section className="engine-grid"><article><BriefcaseBusiness/><small>Operators</small><h2>People who can own outcomes.</h2><p>Commercial execution, customer delivery, operations and project ownership matter as much as technical depth.</p></article><article><Sparkles/><small>Builders</small><h2>AI, product and engineering.</h2><p>We value people who can move from ambiguous workflow to working system and explain the tradeoffs clearly.</p></article><article><Compass/><small>Culture</small><h2>Agency, evidence, ownership.</h2><p>We prefer direct responsibility, visible work and independent thinking over performative busyness.</p></article></section></main></Shell>}

export function AdvisorsPage(){return <Shell><main className="engine-main"><EngineHero kicker="Advisors" title="We want people who sharpen the company, not decorate the page." copy="NOVARCH's advisor network is intended to close real gaps: enterprise sales, German institutions, AI infrastructure, data protection, product strategy, capital and international scale."><InterestForm purpose="novarch_advisors" button="Express interest" note="Submitting interest does not create an advisory relationship; it starts a conversation."/></EngineHero><section className="engine-grid"><article><ShieldCheck/><small>Governance</small><h2>Privacy, compliance and institutional reality.</h2><p>Particularly valuable where AI systems intersect with German and European organizational constraints.</p></article><article><Network/><small>Commercial</small><h2>Distribution, partnerships and enterprise access.</h2><p>Advisors should help NOVARCH make better market decisions and reach serious buyers faster.</p></article><article><Compass/><small>Company building</small><h2>Product, capital and category design.</h2><p>We are interested in experienced people who can challenge assumptions while respecting founder ownership of the company.</p></article></section></main></Shell>}
