import React, { useEffect, useState } from "react";
import axios from "axios";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, CheckCircle2, LockKeyhole } from "lucide-react";
import "./NovaSite.css";
import "./PayPage.css";

const BACKEND_URL=process.env.REACT_APP_BACKEND_URL||"";

function Header(){return <header className="nv-nav"><Link to="/" className="nv-brand"><span className="nv-mark">N</span><span>NOVARCH</span></Link><Link className="nv-nav-cta" to="/">Back to NOVARCH</Link></header>}

export function PayPage(){
 const [params]=useSearchParams(); const [email,setEmail]=useState(""); const [amount,setAmount]=useState(params.get("amount")||""); const [reference,setReference]=useState(params.get("reference")||""); const [note,setNote]=useState(""); const [state,setState]=useState("idle"); const [error,setError]=useState("");
 async function submit(e){e.preventDefault();setState("loading");setError("");try{const r=await axios.post(`${BACKEND_URL}/api/payments/checkout`,{email,amount_eur:amount,reference,note});window.location.assign(r.data.checkout_url)}catch(err){setState("error");setError(err.response?.data?.detail||"Secure checkout could not be started.")}}
 return <div className="nv-site"><Header/><main className="nv-pay"><section><span>Secure payment</span><h1>Pay NOVARCH.</h1><p>Use this page when NOVARCH has given you a project, invoice or payment reference. Your card details are entered on the payment provider's secure checkout — not stored by NOVARCH.</p><div className="nv-pay-trust"><LockKeyhole/><div><b>Reference-linked payment</b><small>Your email, amount and reference are recorded against the payment so we can reconcile it correctly.</small></div></div></section><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Amount in EUR<input type="number" required min="1" max="50000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="500.00"/></label><label>Payment reference<input required minLength="2" maxLength="120" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Project / invoice reference"/></label><label>Note <small>optional</small><textarea maxLength="500" value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything we should know?"/></label><button disabled={state==="loading"}>{state==="loading"?"Opening secure checkout…":"Continue to secure payment"}<ArrowRight size={17}/></button>{params.get("cancelled")&&<p className="nv-pay-msg">Payment was cancelled. Nothing was charged.</p>}{error&&<p className="nv-pay-msg error">{error}</p>}<small className="nv-pay-legal">By continuing you will be redirected to our payment provider. See the <Link to="/datenschutz">privacy notice</Link>.</small></form></main></div>
}

export function PaymentSuccessPage(){const [params]=useSearchParams();const [payment,setPayment]=useState(null);const [loading,setLoading]=useState(true);useEffect(()=>{const id=params.get("session_id");if(!id){setLoading(false);return}axios.get(`${BACKEND_URL}/api/payments/session/${encodeURIComponent(id)}`).then(r=>setPayment(r.data)).catch(()=>{}).finally(()=>setLoading(false))},[params]);return <div className="nv-site"><Header/><main className="nv-pay-success"><CheckCircle2/><span>Payment received</span><h1>Thank you.</h1>{loading?<p>Checking payment record…</p>:payment?<><p>Your NOVARCH payment has been recorded.</p><div><small>Reference</small><b>{payment.reference}</b><small>Amount</small><b>€{payment.amount_eur}</b><small>Status</small><b>{payment.status}</b></div></>:<p>Your checkout completed. If you need confirmation, contact NOVARCH with your payment email.</p>}<Link to="/">Return to NOVARCH <ArrowRight size={15}/></Link></main></div>}
