import React from "react";
import "./App.css";
import { BrowserRouter, Routes, Route, Link } from "react-router-dom";
import NovaHome, { CompanyPage, ManifestoPage } from "./pages/NovaHome";
import { SystemsPage, WorkPage } from "./pages/NovaDeepPages";
import "./lib/siteMetrics";

const BUSINESS = { designation: "NOVARCH", owner: "Massum Abbas", street: "Wiesenweg 21", city: "98693 Ilmenau", country: "Deutschland", email: "novarch-ai@gmail.com" };
function AddressBlock(){return <address><strong>{BUSINESS.designation} — {BUSINESS.owner}</strong><br/>Inhaber: {BUSINESS.owner}<br/>{BUSINESS.street}<br/>{BUSINESS.city}<br/>{BUSINESS.country}</address>}
function LegalLayout({title,children}){return <main className="legal-page"><Link className="legal-back" to="/"><img src="/novarch-mark.svg" alt=""/><span>NOVARCH</span><em>← Zurück</em></Link><article className="legal-card"><p className="legal-eyebrow">NOVARCH — Massum Abbas</p><h1>{title}</h1>{children}</article></main>}
function ImprintPage(){return <LegalLayout title="Impressum"><p>Angaben gemäß § 5 Digitale-Dienste-Gesetz (DDG)</p><AddressBlock/><h2>Kontakt</h2><p>E-Mail: <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a></p><h2>Haftung für Inhalte und Links</h2><p>Wir erstellen die Inhalte dieser Website mit Sorgfalt. Für die Inhalte externer Websites, auf die wir verlinken, sind ausschließlich deren Betreiber verantwortlich.</p><p className="legal-updated">Stand: 20. Juli 2026</p></LegalLayout>}
function PrivacyPage(){return <LegalLayout title="Datenschutzerklärung"><p>Diese Datenschutzerklärung informiert darüber, welche personenbezogenen Daten beim Besuch dieser Website, bei einer Kontaktaufnahme und beim freiwilligen Eintrag in eine NOVARCH-Warteliste verarbeitet werden.</p><h2>1. Verantwortlicher</h2><AddressBlock/><p>E-Mail: <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a></p><h2>2. Hosting und Server-Protokolle</h2><p>Beim Abruf der Website können technisch erforderliche Verbindungsdaten durch die eingesetzte Hosting-Infrastruktur verarbeitet werden. Die Verarbeitung dient der sicheren und zuverlässigen Bereitstellung dieser Website.</p><h2>3. Kontaktaufnahme</h2><p>Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre Angaben, um Ihre Anfrage zu beantworten. Soweit es um die Anbahnung oder Durchführung eines Vertrags geht, ist Art. 6 Abs. 1 lit. b DSGVO die Rechtsgrundlage; im Übrigen Art. 6 Abs. 1 lit. f DSGVO.</p><h2>4. Warteliste / Early Access</h2><p>Wenn Sie sich freiwillig in eine NOVARCH-Warteliste eintragen, verarbeiten wir insbesondere Ihre E-Mail-Adresse, den jeweiligen Wartelisten-Zweck sowie begrenzte Quellen- oder Referral-Angaben, damit wir Ihre Anmeldung verwalten und Sie zu diesem Zweck kontaktieren können. Die Daten werden in der von NOVARCH eingesetzten Backend-Infrastruktur gespeichert und können mit unserem E-Mail-Kontaktmanagement synchronisiert werden.</p><p>Sie können der weiteren Kontaktaufnahme jederzeit per E-Mail widersprechen bzw. eine Löschung Ihrer Wartelisten-Daten verlangen.</p><h2>5. Reichweiten- und Interaktionsmessung</h2><p>NOVARCH kann in begrenztem Umfang technische Nutzungsereignisse, insbesondere Seitenaufrufe und Interaktionen, erfassen. Die Messung dient der technischen und wirtschaftlichen Bewertung der Website und von Kampagnen.</p><h2>6. Externe Links</h2><p>Links zu externen Angeboten übertragen Daten erst, wenn Sie den jeweiligen Link aufrufen.</p><h2>7. Ihre Rechte</h2><p>Sie haben nach Maßgabe der DSGVO insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch.</p><h2>8. Beschwerderecht</h2><p>Sie können sich bei einer Datenschutzaufsichtsbehörde beschweren. Für Thüringen: Thüringer Landesbeauftragter für den Datenschutz und die Informationsfreiheit, Häßlerstraße 8, 99096 Erfurt.</p><h2>9. Aktualisierung</h2><p>Wir aktualisieren diese Erklärung, wenn sich eingesetzte Dienste oder rechtliche Anforderungen ändern.</p><p className="legal-updated">Stand: 12. August 2026</p></LegalLayout>}
function App(){return <div className="App"><BrowserRouter><Routes><Route path="/" element={<NovaHome/>}/><Route path="/en" element={<NovaHome/>}/><Route path="/systems" element={<SystemsPage/>}/><Route path="/work" element={<WorkPage/>}/><Route path="/company" element={<CompanyPage/>}/><Route path="/manifesto" element={<ManifestoPage/>}/><Route path="/impressum" element={<ImprintPage/>}/><Route path="/datenschutz" element={<PrivacyPage/>}/></Routes></BrowserRouter></div>}
export default App;
