import React from "react";
import "./App.css";
import { BrowserRouter, Routes, Route, Link } from "react-router-dom";
import NovaHome, { CompanyPage, ManifestoPage, WorkflowReviewPage } from "./pages/NovaHome";
import { SystemsPage, WorkPage } from "./pages/NovaDeepPages";
import { LaunchPage, CommunityPage, TalentPage, AdvisorsPage } from "./pages/EnginePages";
import { PayPage, PaymentSuccessPage } from "./pages/PayPage";
import "./lib/siteMetrics";
const BUSINESS={designation:"NOVARCH",owner:"Massum Abbas",street:"Wiesenweg 21",city:"98693 Ilmenau",country:"Deutschland",email:"novarch-ai@gmail.com"};
function AddressBlock(){return <address><strong>{BUSINESS.designation} — {BUSINESS.owner}</strong><br/>Inhaber: {BUSINESS.owner}<br/>{BUSINESS.street}<br/>{BUSINESS.city}<br/>{BUSINESS.country}</address>}
function LegalLayout({title,children}){return <main className="legal-page"><Link className="legal-back" to="/"><img src="/novarch-mark.svg" alt=""/><span>NOVARCH</span><em>← Zurück</em></Link><article className="legal-card"><p className="legal-eyebrow">NOVARCH — Massum Abbas</p><h1>{title}</h1>{children}</article></main>}
function ImprintPage(){return <LegalLayout title="Impressum"><p>Angaben gemäß § 5 Digitale-Dienste-Gesetz (DDG)</p><AddressBlock/><h2>Kontakt</h2><p>E-Mail: <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a></p><h2>Haftung für Inhalte und Links</h2><p>Wir erstellen die Inhalte dieser Website mit Sorgfalt. Für die Inhalte externer Websites, auf die wir verlinken, sind ausschließlich deren Betreiber verantwortlich.</p><p className="legal-updated">Stand: 20. Juli 2026</p></LegalLayout>}
function PrivacyPage(){return <LegalLayout title="Datenschutzerklärung"><p>Diese Datenschutzerklärung informiert darüber, welche personenbezogenen Daten beim Besuch dieser Website, bei einer Kontaktaufnahme, bei einer freiwilligen Wartelisten-Anmeldung und im Zusammenhang mit Zahlungen verarbeitet werden.</p><h2>1. Verantwortlicher</h2><AddressBlock/><p>E-Mail: <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a></p><h2>2. Hosting und Server-Protokolle</h2><p>Beim Abruf der Website können technisch erforderliche Verbindungsdaten durch die eingesetzte Hosting-Infrastruktur verarbeitet werden. Die Verarbeitung dient der sicheren und zuverlässigen Bereitstellung dieser Website.</p><h2>3. Kontaktaufnahme</h2><p>Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre Angaben, um Ihre Anfrage zu beantworten.</p><h2>4. Warteliste / Early Access</h2><p>Wenn Sie sich freiwillig in eine NOVARCH-Warteliste eintragen, verarbeiten wir insbesondere Ihre E-Mail-Adresse, den jeweiligen Wartelisten-Zweck sowie begrenzte Quellen- oder Referral-Angaben.</p><h2>5. Zahlungen</h2><p>Wenn Sie eine Zahlung an NOVARCH über die Website einleiten, verarbeiten wir die zur Zuordnung erforderlichen Angaben. Die eigentliche Zahlungsabwicklung erfolgt über den eingesetzten Zahlungsdienstleister.</p><h2>6. Ihre Rechte</h2><p>Sie haben nach Maßgabe der DSGVO insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch.</p><p className="legal-updated">Stand: 12. August 2026</p></LegalLayout>}
function App(){return <div className="App"><BrowserRouter><Routes><Route path="/" element={<NovaHome/>}/><Route path="/en" element={<NovaHome/>}/><Route path="/systems" element={<SystemsPage/>}/><Route path="/work" element={<WorkPage/>}/><Route path="/company" element={<CompanyPage/>}/><Route path="/manifesto" element={<ManifestoPage/>}/><Route path="/workflow-review" element={<WorkflowReviewPage/>}/><Route path="/launch" element={<LaunchPage/>}/><Route path="/community" element={<CommunityPage/>}/><Route path="/talent" element={<TalentPage/>}/><Route path="/advisors" element={<AdvisorsPage/>}/><Route path="/pay" element={<PayPage/>}/><Route path="/pay/success" element={<PaymentSuccessPage/>}/><Route path="/impressum" element={<ImprintPage/>}/><Route path="/datenschutz" element={<PrivacyPage/>}/></Routes></BrowserRouter></div>}
export default App;